# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
# include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
  #  prefer_single_quotes: error
  #  file_names: ignore
  #  prefer_const_constructors: ignore
  #  use_key_in_widget_constructors: ignore
  #  prefer_final_fields: ignore
  #  unused_field: ignore
  #  unused_local_variable: ignore
  #  unused_element: ignore
  #  new_with_undefined_constructor_default: ignore
   unused_import: ignore
   unnecessary_null_comparison: ignore
   unused_field: ignore
   deprecated_member_use: ignore
   unused_local_variable: ignore
   unused_element: ignore
linter:
  rules:
  #  prefer_single_quotes: true
